# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calprojects.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from os import remove
from tkinter import Label
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:10px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_0.sizePolicy().hasHeightForWidth())
        self.pushButton_0.setSizePolicy(sizePolicy)
        self.pushButton_0.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 5, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.equalbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.equalbutton.sizePolicy().hasHeightForWidth())
        self.equalbutton.setSizePolicy(sizePolicy)
        self.equalbutton.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    \n"
"    background-color: rgb(97, 221, 255);\n"
"}\n"
"")
        self.equalbutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/equalsign_81021.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.equalbutton.setIcon(icon)
        self.equalbutton.setObjectName("equalbutton")
        self.gridLayout.addWidget(self.equalbutton, 5, 3, 1, 1)
        self.DelButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.DelButton.sizePolicy().hasHeightForWidth())
        self.DelButton.setSizePolicy(sizePolicy)
        self.DelButton.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.DelButton.setObjectName("DelButton")
        self.gridLayout.addWidget(self.DelButton, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 3, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 1, 1, 1)
        self.additionbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.additionbutton.sizePolicy().hasHeightForWidth())
        self.additionbutton.setSizePolicy(sizePolicy)
        self.additionbutton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 44, 107);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"")
        self.additionbutton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.additionbutton.setIcon(icon1)
        self.additionbutton.setObjectName("additionbutton")
        self.gridLayout.addWidget(self.additionbutton, 1, 3, 1, 1)
        self.divisionbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.divisionbutton_2.sizePolicy().hasHeightForWidth())
        self.divisionbutton_2.setSizePolicy(sizePolicy)
        self.divisionbutton_2.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    \n"
"    background-color: rgb(97, 221, 255);\n"
"}\n"
"")
        self.divisionbutton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/divisionsign_81003.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.divisionbutton_2.setIcon(icon2)
        self.divisionbutton_2.setObjectName("divisionbutton_2")
        self.gridLayout.addWidget(self.divisionbutton_2, 4, 3, 1, 1)
        self.substractionbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.substractionbutton.sizePolicy().hasHeightForWidth())
        self.substractionbutton.setSizePolicy(sizePolicy)
        self.substractionbutton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 44, 107);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    \n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"")
        self.substractionbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.substractionbutton.setIcon(icon3)
        self.substractionbutton.setObjectName("substractionbutton")
        self.gridLayout.addWidget(self.substractionbutton, 2, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.multiplicationbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.multiplicationbutton.sizePolicy().hasHeightForWidth())
        self.multiplicationbutton.setSizePolicy(sizePolicy)
        self.multiplicationbutton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 44, 107);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    \n"
"        background-color: rgb(255, 255, 0);\n"
"}\n"
"")
        self.multiplicationbutton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.multiplicationbutton.setIcon(icon4)
        self.multiplicationbutton.setObjectName("multiplicationbutton")
        self.gridLayout.addWidget(self.multiplicationbutton, 3, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 4, 2, 1, 1)
        self.pointbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.pointbutton.sizePolicy().hasHeightForWidth())
        self.pointbutton.setSizePolicy(sizePolicy)
        self.pointbutton.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    \n"
"    background-color: rgb(97, 221, 255);\n"
"}\n"
"")
        self.pointbutton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/primitivedot_106373.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pointbutton.setIcon(icon5)
        self.pointbutton.setObjectName("pointbutton")
        self.gridLayout.addWidget(self.pointbutton, 5, 2, 1, 1)
        self.Clearbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.Clearbutton.sizePolicy().hasHeightForWidth())
        self.Clearbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Clearbutton.setFont(font)
        self.Clearbutton.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"border-radius:35px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(229, 228, 255);\n"
"    background-color: rgb(124, 119, 255);\n"
"}\n"
"")
        self.Clearbutton.setObjectName("Clearbutton")
        self.gridLayout.addWidget(self.Clearbutton, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def method_1(self):
            a=self.label.text()
            self.label.setText(a+"1")
            
    def method_2(self):
            a=self.label.text()
            self.label.setText(a+"2")
            
    def method_3(self):
            a=self.label.text()
            self.label.setText(a + "3")
            
    def method_4(self):
            a=self.label.text()
            self.label.setText(a+"4")
            
    def method_5(self):
            a=self.label.text()
            self.label.setText(a+"5")
            
            
    def method_6(self):
             a=self.label.text()
             self.label.setText(a+"6")
             
    def method_7(self):
            a=self.label.text()
            self.label.setText(a +"7") 
            
    def method_8(self):
            a=self.label.text()
            self.label.setText(a+"8")
            
    def method_9(self):
            a=self.label.text()
            self.label.setText(a+"9")
            
    def method_0(self):
            a=self.label.text()
            self.label.setText(a+"0") 
            
    def method_Clear(self):
            a=self.label.text()
            self.label.setText("")
            
    def  method_addition(self):
            a=self.label.text()
            self.label.setText( a + "+")
            
    def method_multiplication(self):
            a=self.label.text()
            self.label.setText( a + "*")        
                                                          
    def method_division(self):
            a=self.label.text()
            self.label.setText(a + "/") 
            
    def method_substraction(self):
            a=self.label.text()
            self.label.setText(a+"-")        
            
            
    def method_point(self):
            a=self.label.text()
            self.label.setText(a+".")
            
            
    def method_equal(self):
            a=self.label.text()
            try:
                    
                answer=eval(a)
                self.label.setText(str(answer)) 
            except:
                    self.label.setText("wrong syntax")    
                
    
    def method_Del(self):
            a=self.label.text()
            self.label.setText(a[ : len(a)-1]) 
                    
                            
                                    
                            
            
                

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.DelButton.setText(_translate("MainWindow", "Del"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.Clearbutton.setText(_translate("MainWindow", "Clear"))
        # events on the pushbuttons
        self.pushButton_0.clicked.connect(self.method_0)
        self.pushButton_1.clicked.connect(self.method_1)
        self.pushButton_2.clicked.connect(self.method_2)
        self.pushButton_3.clicked.connect(self.method_3)
        self.pushButton_4.clicked.connect(self.method_4)
        self.pushButton_5.clicked.connect(self.method_5)
        self.pushButton_6.clicked.connect(self.method_6)
        self.pushButton_7.clicked.connect(self.method_7)
        self.pushButton_8.clicked.connect(self.method_8)
        self.pushButton_9.clicked.connect(self.method_9)
        self.DelButton.clicked.connect(self.method_Del)
        self.Clearbutton.clicked.connect(self.method_Clear)
        # events on operations
        self.additionbutton.clicked.connect(self.method_addition)
        self.multiplicationbutton.clicked.connect(self.method_multiplication)
        self.divisionbutton_2.clicked.connect(self.method_division)
        self.equalbutton.clicked.connect(self.method_equal)
        self.pointbutton.clicked.connect(self.method_point)
        self.substractionbutton.clicked.connect(self.method_substraction)
        
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())